./trainpwcconnector13_AH_chairs.sh
./trainpwcconnector13_AH_kitti.sh
./trainpwcconnector13_AH_sintel.sh
./trainpwcconnector13_AH_things.sh
./trainpwcconnector13_AI_chairs.sh
./trainpwcconnector13_AI_kitti.sh
./trainpwcconnector13_AI_sintel.sh
./trainpwcconnector13_AI_things.sh
./trainpwcconnector13_AW_chairs.sh
./trainpwcconnector13_AW_kitti.sh
./trainpwcconnector13_AW_sintel.sh
./trainpwcconnector13_AW_things.sh
./trainpwcconnector13_HA_chairs.sh
./trainpwcconnector13_HA_kitti.sh
./trainpwcconnector13_HA_sintel.sh
./trainpwcconnector13_HA_things.sh
./trainpwcconnector13_HI_chairs.sh
./trainpwcconnector13_HI_kitti.sh
./trainpwcconnector13_HI_sintel.sh
./trainpwcconnector13_HI_things.sh
./trainpwcconnector13_HW_chairs.sh
./trainpwcconnector13_HW_kitti.sh
./trainpwcconnector13_HW_sintel.sh
./trainpwcconnector13_HW_things.sh
./trainpwcconnector13_IA_chairs.sh
./trainpwcconnector13_IA_kitti.sh
./trainpwcconnector13_IA_sintel.sh
./trainpwcconnector13_IA_things.sh
./trainpwcconnector13_IH_chairs.sh
./trainpwcconnector13_IH_kitti.sh
./trainpwcconnector13_IH_sintel.sh
./trainpwcconnector13_IH_things.sh
./trainpwcconnector13_IW_chairs.sh
./trainpwcconnector13_IW_kitti.sh
./trainpwcconnector13_IW_sintel.sh
./trainpwcconnector13_IW_things.sh
./trainpwcconnector13_WA_chairs.sh
./trainpwcconnector13_WA_kitti.sh
./trainpwcconnector13_WA_sintel.sh
./trainpwcconnector13_WA_things.sh
./trainpwcconnector13_WH_chairs.sh
./trainpwcconnector13_WH_kitti.sh
./trainpwcconnector13_WH_sintel.sh
./trainpwcconnector13_WH_things.sh
./trainpwcconnector13_WI_chairs.sh
./trainpwcconnector13_WI_kitti.sh
./trainpwcconnector13_WI_sintel.sh
./trainpwcconnector13_WI_things.sh
