./trainpwcconnector13_AH_chairs.sh
./trainpwcconnector13_AH_kitti.sh
./trainpwcconnector13_AH_sintel.sh
./trainpwcconnector13_AH_things.sh
./trainpwcconnector13_AI_chairs.sh
./trainpwcconnector13_AI_kitti.sh
./trainpwcconnector13_AI_sintel.sh
./trainpwcconnector13_AI_things.sh
./trainpwcconnector13_HA_chairs.sh
./trainpwcconnector13_HA_kitti.sh
./trainpwcconnector13_HA_sintel.sh
./trainpwcconnector13_HA_things.sh
./trainpwcconnector13_HI_chairs.sh
./trainpwcconnector13_HI_kitti.sh
./trainpwcconnector13_HI_sintel.sh
./trainpwcconnector13_HI_things.sh
./trainpwcconnector13_IA_chairs.sh
./trainpwcconnector13_IA_kitti.sh
./trainpwcconnector13_IA_sintel.sh
./trainpwcconnector13_IA_things.sh
./trainpwcconnector13_IH_chairs.sh
./trainpwcconnector13_IH_kitti.sh
./trainpwcconnector13_IH_sintel.sh
./trainpwcconnector13_IH_things.sh